//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSFUF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDB
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Office { get; set; }
        public string Region { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
