//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSFUF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string OrgName { get; set; }
        public string ArchiveNo { get; set; }
        public string OrgTIN { get; set; }
        public Nullable<int> DocCount { get; set; }
        public Nullable<int> Allowance { get; set; }
        public string PhoneNo { get; set; }
        public string GovIDNo { get; set; }
        public string PrivateIDNo { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DateRecieved { get; set; }
        public Nullable<System.DateTime> DateTransfered { get; set; }
        public string Gender { get; set; }
        public string DocStatus { get; set; }
        public string AssignedExpert { get; set; }
        public string Bank { get; set; }
        public string PensionerID { get; set; }
        public string ApprovalStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string BankBranch { get; set; }
        public string Region { get; set; }
        public string PayExpert { get; set; }
        public Nullable<System.DateTime> PayLetterPrepDay { get; set; }
        public Nullable<System.DateTime> issueDate { get; set; }
        public Nullable<System.DateTime> when { get; set; }
        public string Recipent { get; set; }
        public string RefNo { get; set; }
        public string RegionForUser { get; set; }
    }
}
