//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSFUF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string OrgName { get; set; }
        public string OrgTIN { get; set; }
        public Nullable<int> Allowance { get; set; }
        public string PhoneNo { get; set; }
        public string PrivateIDNo { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DateRegistered { get; set; }
        public Nullable<System.DateTime> DateTransferedToCon { get; set; }
        public string Gender { get; set; }
        public string RegisteredExpertName { get; set; }
        public string ConExpertName { get; set; }
        public string DocStatusOfReg { get; set; }
        public string DocStatusOfCon { get; set; }
        public string AssignedConExpert { get; set; }
        public Nullable<System.DateTime> TaskRecievedDateCon { get; set; }
        public Nullable<System.DateTime> DateTransferedToDecFromCon { get; set; }
        public string AssignedDecExpert { get; set; }
        public Nullable<System.DateTime> DateRecievedToDecExpert { get; set; }
        public Nullable<System.DateTime> DateTransferedOfDecExpert { get; set; }
        public string DocStatusOfDec { get; set; }
        public string AssignedApprover { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDateRecived { get; set; }
        public string AssignedRegion { get; set; }
        public string PaymentExpert { get; set; }
        public Nullable<System.DateTime> PaymentsWhen { get; set; }
        public Nullable<System.DateTime> PayLetterPrepDayForRep { get; set; }
        public Nullable<System.DateTime> PayIssueDateForRep { get; set; }
        public string ReciepentPayExpForRep { get; set; }
        public string ReferenceNoForReport { get; set; }
        public string RegionRegistered { get; set; }
    }
}
